### ISSUE TITLE
[FEAT] 사용자 관리(member) 데이터 통신 (1)

### ISSUE THREAD

**Issue by rlawjd10** [hi-sujung/msa-member#9]
📌 이슈 내용
Member 레포지토리 도커 이미지 만들기 및 데이터 통신

💼 작업 목록

- [x] member repo - Dockerfile 작성
- [x] member repo - Docker hub에 이미지 올리기

**Comment by imsuhyen** [comment]
좋은 이슈 감사합니다 :)
